name: Publish
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload to a release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PUBLISH_GITHUB_ACTION }}
          file: '.github/actions/*' # the folder which has all the files that you want to release
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          repo_name: test-publish-actions